package main.java.com.riddleroad.batmobilechronicles;

import java.util.HashMap;
import java.util.Map;

public class MovieTrivia {
    public static final Map<Integer, String[]> triviaMap = new HashMap<>();

    static {
        triviaMap.put(1, new String[]{"The Shawshank Redemption", "What is the name of the prison where the movie takes place?", "Shawshank State Penitentiary", "Alcatraz", "Rykers Island", "San Quentin"});
        triviaMap.put(2, new String[]{"The Godfather", "Who is the head of the Corleone family?", "Vito Corleone", "Michael Corleone", "Sonny Corleone", "Tom Hagen"});
        triviaMap.put(3, new String[]{"The Dark Knight", "Which actor played the Joker in *The Dark Knight*?", "Heath Ledger", "Jack Nicholson", "Jared Leto", "Mark Hamill"});
        triviaMap.put(4, new String[]{"Forrest Gump", "What sport does Forrest Gump excel in after being drafted into the army?", "Ping Pong", "Football", "Basketball", "Tennis"});
        triviaMap.put(5, new String[]{"Pulp Fiction", "Who directed *Pulp Fiction*?", "Quentin Tarantino", "Martin Scorsese", "Francis Ford Coppola", "Steven Spielberg"});
        triviaMap.put(6, new String[]{"Inception", "What is the name of the main character played by Leonardo DiCaprio?", "Dom Cobb", "Arthur", "Robert Fischer", "Mal Cobb"});
        triviaMap.put(7, new String[]{"Fight Club", "What is the first rule of Fight Club?", "You do not talk about Fight Club", "You do not fight back", "You fight to win", "You never stop fighting"});
        triviaMap.put(8, new String[]{"The Matrix", "What is the name of the main character in *The Matrix*?", "Neo", "Trinity", "Morpheus", "Agent Smith"});
        triviaMap.put(9, new String[]{"The Silence of the Lambs", "Which actor plays the role of Hannibal Lecter?", "Anthony Hopkins", "Jack Nicholson", "Johnny Depp", "Morgan Freeman"});
        triviaMap.put(10, new String[]{"Goodfellas", "Who directed *Goodfellas*?", "Martin Scorsese", "Francis Ford Coppola", "Quentin Tarantino", "Stanley Kubrick"});
        triviaMap.put(11, new String[]{"The Departed", "Which city is the setting of *The Departed*?", "Boston", "New York", "Chicago", "Los Angeles"});
        triviaMap.put(12, new String[]{"Schindler's List", "Who directed *Schindler's List*?", "Steven Spielberg", "Martin Scorsese", "Ridley Scott", "Christopher Nolan"});
        triviaMap.put(13, new String[]{"The Lion King", "What is the name of Simba’s father?", "Mufasa", "Scar", "Zazu", "Timon"});
        triviaMap.put(14, new String[]{"Interstellar", "What is the primary goal of the mission in *Interstellar*?", "Find a new habitable planet", "Save Earth", "Defeat the aliens", "Travel to the past"});
        triviaMap.put(15, new String[]{"Star Wars: Episode IV", "Who is Luke Skywalker's father?", "Darth Vader", "Obi-Wan Kenobi", "Han Solo", "Yoda"});
        triviaMap.put(16, new String[]{"Titanic", "Who directed *Titanic*?", "James Cameron", "Steven Spielberg", "Martin Scorsese", "Ridley Scott"});
        triviaMap.put(17, new String[]{"The Godfather Part II", "Who plays Michael Corleone in *The Godfather Part II*?", "Al Pacino", "Marlon Brando", "James Caan", "Robert Duvall"});
        triviaMap.put(18, new String[]{"Casablanca", "In *Casablanca*, what is the name of the nightclub owned by Rick?", "Rick's Café Américain", "Sam's Bar", "The Blue Parrot", "La Belle Époque"});
        triviaMap.put(19, new String[]{"The Good, the Bad, and the Ugly", "Who plays 'Blondie' (the Good) in *The Good, the Bad, and the Ugly*?", "Clint Eastwood", "Lee Van Cleef", "Eli Wallach", "Charles Bronson"});
        triviaMap.put(20, new String[]{"Gone with the Wind", "Who played Scarlett O'Hara in *Gone with the Wind*?", "Vivien Leigh", "Audrey Hepburn", "Bette Davis", "Ingrid Bergman"});
        triviaMap.put(21, new String[]{"Citizen Kane", "What is the last word spoken by Charles Foster Kane in *Citizen Kane*?", "Rosebud", "Goodbye", "Eureka", "Nevermore"});
        triviaMap.put(22, new String[]{"12 Angry Men", "In *12 Angry Men*, how many jurors initially vote 'guilty'?", "11", "12", "9", "8"});
        triviaMap.put(23, new String[]{"The Shawshank Redemption", "Who played the character of Andy Dufresne?", "Tim Robbins", "Morgan Freeman", "Clint Eastwood", "Kevin Spacey"});
        triviaMap.put(24, new String[]{"The Prestige", "Who directed *The Prestige*?", "Christopher Nolan", "Martin Scorsese", "David Fincher", "Quentin Tarantino"});
        triviaMap.put(25, new String[]{"Back to the Future", "What is the name of the time-traveling vehicle?", "DeLorean", "TARDIS", "Time Machine", "Flux Capacitor"});
        triviaMap.put(26, new String[]{"The Green Mile", "Who played the character of John Coffey in *The Green Mile*?", "Michael Clarke Duncan", "Tom Hanks", "Gary Sinise", "James Cromwell"});
        triviaMap.put(27, new String[]{"The Usual Suspects", "Who is revealed to be Keyser Söze in *The Usual Suspects*?", "Roger 'Verbal' Kint", "Dean Keaton", "Todd Hockney", "Michael McManus"});
        triviaMap.put(28, new String[]{"The Shining", "Which actor plays Jack Torrance in *The Shining*?", "Jack Nicholson", "Tom Cruise", "Robert De Niro", "Johnny Depp"});
        triviaMap.put(29, new String[]{"A Clockwork Orange", "Who directed *A Clockwork Orange*?", "Stanley Kubrick", "Alfred Hitchcock", "Quentin Tarantino", "Martin Scorsese"});
        triviaMap.put(30, new String[]{"Jaws", "Who directed *Jaws*?", "Steven Spielberg", "George Lucas", "Ridley Scott", "Martin Scorsese"});
        triviaMap.put(31, new String[]{"The Dark Knight", "Who plays Bruce Wayne/Batman in *The Dark Knight*?", "Christian Bale", "Michael Keaton", "Ben Affleck", "Val Kilmer"});
        triviaMap.put(32, new String[]{"Gladiator", "Who plays the character of Maximus in *Gladiator*?", "Russell Crowe", "Brad Pitt", "Tom Cruise", "Matt Damon"});
        triviaMap.put(33, new String[]{"The Big Lebowski", "What is the nickname of the main character played by Jeff Bridges?", "The Dude", "Big Man", "Johnny Utah", "Dr. Dude"});
        triviaMap.put(34, new String[]{"The Social Network", "Who plays Mark Zuckerberg in *The Social Network*?", "Jesse Eisenberg", "Andrew Garfield", "Armie Hammer", "Justin Timberlake"});
        triviaMap.put(35, new String[]{"The Terminator", "Which actor plays the Terminator in *The Terminator*?", "Arnold Schwarzenegger", "Sylvester Stallone", "Bruce Willis", "Jean-Claude Van Damme"});
        triviaMap.put(36, new String[]{"Pulp Fiction", "Who plays Vincent Vega in *Pulp Fiction*?", "John Travolta", "Bruce Willis", "Samuel L. Jackson", "Harvey Keitel"});
        triviaMap.put(37, new String[]{"The Matrix", "Who directed *The Matrix*?", "The Wachowskis", "George Lucas", "Steven Spielberg", "Ridley Scott"});
        triviaMap.put(38, new String[]{"The Breakfast Club", "What is the nickname of the character played by Judd Nelson in *The Breakfast Club*?", "John Bender", "Brian Johnson", "Claire Standish", "Allison Reynolds"});
        triviaMap.put(39, new String[]{"The Godfather Part II", "What is the name of Michael Corleone's wife in *The Godfather Part II*?", "Kay Adams", "Connie Corleone", "Apollonia", "Mia Farrow"});
        triviaMap.put(40, new String[]{"The Grand Budapest Hotel", "Who directed *The Grand Budapest Hotel*?", "Wes Anderson", "Martin Scorsese", "Quentin Tarantino", "Tim Burton"});
        triviaMap.put(41, new String[]{"The Sixth Sense", "What twist ending is revealed in *The Sixth Sense*?", "Bruce Willis's character is dead", "The boy is a ghost", "The therapist is his father", "The girl was never alive"});
        triviaMap.put(42, new String[]{"The Lion King", "Who voices the character of Mufasa?", "James Earl Jones", "Jeremy Irons", "Matthew Broderick", "John Oliver"});
        triviaMap.put(43, new String[]{"Inglourious Basterds", "Who directed *Inglourious Basterds*?", "Quentin Tarantino", "Steven Spielberg", "Ridley Scott", "Martin Scorsese"});
        triviaMap.put(44, new String[]{"Se7en", "What is the theme of the film *Se7en*?", "The Seven Deadly Sins", "A murder mystery", "Detective investigation", "The search for God"});
        triviaMap.put(45, new String[]{"Shutter Island", "Who directed *Shutter Island*?", "Martin Scorsese", "Christopher Nolan", "Ridley Scott", "Steven Spielberg"});
        triviaMap.put(46, new String[]{"The Dark Knight Rises", "Who plays Bane in *The Dark Knight Rises*?", "Tom Hardy", "Christian Bale", "Michael Caine", "Gary Oldman"});
        triviaMap.put(47, new String[]{"Scarface", "Who plays Tony Montana in *Scarface*?", "Al Pacino", "Robert De Niro", "Jack Nicholson", "Johnny Depp"});
        triviaMap.put(48, new String[]{"The Departed", "Who is the rat in *The Departed*?", "Matt Damon", "Leonardo DiCaprio", "Jack Nicholson", "Mark Wahlberg"});
        triviaMap.put(49, new String[]{"A Beautiful Mind", "Who played John Nash in *A Beautiful Mind*?", "Russell Crowe", "Matt Damon", "Tom Hanks", "Johnny Depp"});
        triviaMap.put(50, new String[]{"The Wizard of Oz", "What is the name of the wizard in *The Wizard of Oz*?", "The Wizard of Oz", "The Great Wizard", "Professor Marvel", "The Tin Man"});
        triviaMap.put(51, new String[]{"The Breakfast Club", "Who plays the character of Brian Johnson?", "Anthony Michael Hall", "Judd Nelson", "Emilio Estevez", "Molly Ringwald"});
        triviaMap.put(52, new String[]{"The Godfather Part III", "Who is the director of *The Godfather Part III*?", "Francis Ford Coppola", "Martin Scorsese", "Ridley Scott", "Quentin Tarantino"});
        triviaMap.put(53, new String[]{"The Exorcist", "What is the name of the possessed girl in *The Exorcist*?", "Regan MacNeil", "Linda Blair", "Chris MacNeil", "Father Karras"});
        triviaMap.put(54, new String[]{"The Great Gatsby", "Who played Jay Gatsby in *The Great Gatsby*?", "Leonardo DiCaprio", "Brad Pitt", "Robert Pattinson", "Matthew McConaughey"});
        triviaMap.put(55, new String[]{"Saving Private Ryan", "What war is depicted in *Saving Private Ryan*?", "World War II", "World War I", "Vietnam War", "Korean War"});
        triviaMap.put(56, new String[]{"The Sound of Music", "What is the name of the family in *The Sound of Music*?", "Von Trapp", "Smith", "Richards", "Bennett"});
        triviaMap.put(57, new String[]{"Deadpool", "Who plays the role of Wade Wilson/Deadpool?", "Ryan Reynolds", "Chris Hemsworth", "Hugh Jackman", "Ben Affleck"});
        triviaMap.put(58, new String[]{"The Princess Bride", "Who plays the character of Westley?", "Cary Elwes", "Chris Hemsworth", "Harrison Ford", "Matt Damon"});
        triviaMap.put(59, new String[]{"The Iron Giant", "Who directed *The Iron Giant*?", "Brad Bird", "John Lasseter", "Steven Spielberg", "Henry Selick"});
        triviaMap.put(60, new String[]{"Jurassic Park", "What is the name of the park in *Jurassic Park*?", "Isla Nublar", "Isla Sorna", "Costa Rica", "San Diego"});
        triviaMap.put(61, new String[]{"The Truman Show", "Who plays Truman in *The Truman Show*?", "Jim Carrey", "Robin Williams", "Tom Hanks", "Jack Nicholson"});
        triviaMap.put(62, new String[]{"The Matrix Reloaded", "Which character betrays Neo in *The Matrix Reloaded*?", "The Oracle", "Morpheus", "Agent Smith", "The Architect"});
        triviaMap.put(63, new String[]{"The Prestige", "Who plays Alfred Borden in *The Prestige*?", "Christian Bale", "Hugh Jackman", "Michael Caine", "Scarlett Johansson"});
        triviaMap.put(64, new String[]{"Die Hard", "Where does *Die Hard* take place?", "Nakatomi Plaza", "Skyscraper", "Pentagon", "New York"});
        triviaMap.put(65, new String[]{"Mad Max: Fury Road", "What is the name of the protagonist in *Mad Max: Fury Road*?", "Max Rockatansky", "Furiosa", "Immortan Joe", "Nux"});
        triviaMap.put(66, new String[]{"The Incredibles", "What is the name of the main villain in *The Incredibles*?", "Syndrome", "The Underminer", "The Mole", "Frozone"});
        triviaMap.put(67, new String[]{"Catch Me If You Can", "Who plays Frank Abagnale Jr. in *Catch Me If You Can*?", "Leonardo DiCaprio", "Matt Damon", "Tom Hanks", "Brad Pitt"});
        triviaMap.put(68, new String[]{"Slumdog Millionaire", "Where does *Slumdog Millionaire* take place?", "Mumbai", "New Delhi", "Kolkata", "Bangalore"});
        triviaMap.put(69, new String[]{"The Conjuring", "Who directed *The Conjuring*?", "James Wan", "John Carpenter", "David Fincher", "M. Night Shyamalan"});
        triviaMap.put(70, new String[]{"The Hangover", "Where does *The Hangover* take place?", "Las Vegas", "Los Angeles", "Chicago", "New York"});
        triviaMap.put(71, new String[]{"The Great Dictator", "Who directed *The Great Dictator*?", "Charlie Chaplin", "Buster Keaton", "Harold Lloyd", "Stan Laurel"});
        triviaMap.put(72, new String[]{"The Wolf of Wall Street", "Who played Jordan Belfort in *The Wolf of Wall Street*?", "Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Johnny Depp"});
        triviaMap.put(73, new String[]{"Her", "What is the name of the AI in *Her*?", "Samantha", "Cortana", "Alexa", "Hal"});
        triviaMap.put(74, new String[]{"Whiplash", "What is the name of the music school in *Whiplash*?", "Shaffer Conservatory", "Berklee School of Music", "Juilliard", "Royal Academy"});
        triviaMap.put(75, new String[]{"Guardians of the Galaxy", "Who voices Rocket Raccoon in *Guardians of the Galaxy*?", "Bradley Cooper", "Chris Pratt", "Vin Diesel", "Dave Bautista"});
        triviaMap.put(76, new String[]{"The Revenant", "What is the name of the frontiersman played by Leonardo DiCaprio?", "Hugh Glass", "John Fitzgerald", "Jim Bridger", "Tom Hardy"});
        triviaMap.put(77, new String[]{"Frozen", "What is the name of the snowman character in *Frozen*?", "Olaf", "Sven", "Kristoff", "Hans"});
        triviaMap.put(78, new String[]{"La La Land", "Who played the role of Mia in *La La Land*?", "Emma Stone", "Nicole Kidman", "Natalie Portman", "Margot Robbie"});
        triviaMap.put(79, new String[]{"Zootopia", "Who is the voice of Judy Hopps in *Zootopia*?", "Ginnifer Goodwin", "Shakira", "Jennifer Lopez", "Sofia Vergara"});
        triviaMap.put(80, new String[]{"Black Panther", "Who played T'Challa/Black Panther in *Black Panther*?", "Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Forest Whitaker"});
        triviaMap.put(81, new String[]{"The Incredibles 2", "What is the name of the new villain in *The Incredibles 2*?", "Screenslaver", "The Underminer", "Syndrome", "Frozone"});
        triviaMap.put(82, new String[]{"Coco", "What is the name of the protagonist in *Coco*?", "Miguel Rivera", "Héctor", "Ernesto de la Cruz", "Mama Imelda"});
        triviaMap.put(83, new String[]{"The Lion King (2019)", "Who voices Simba in the 2019 live-action *The Lion King*?", "Donald Glover", "Matthew Broderick", "James Earl Jones", "Seth Rogen"});
        triviaMap.put(84, new String[]{"Spider-Man: Into the Spider-Verse", "Which character is voiced by Shameik Moore in *Spider-Man: Into the Spider-Verse*?", "Miles Morales", "Peter Parker", "Kingpin", "Gwen Stacy"});
        triviaMap.put(85, new String[]{"The Nightmare Before Christmas", "Who directed *The Nightmare Before Christmas*?", "Tim Burton", "Henry Selick", "Steven Spielberg", "George Lucas"});
        triviaMap.put(86, new String[]{"The Lego Movie", "What is the name of the hero in *The Lego Movie*?", "Emmet Brickowski", "Wildstyle", "Benny", "Unikitty"});
        triviaMap.put(87, new String[]{"Wonder Woman", "Who played Diana Prince/Wonder Woman in *Wonder Woman*?", "Gal Gadot", "Scarlett Johansson", "Brie Larson", "Charlize Theron"});
        triviaMap.put(88, new String[]{"Interstellar", "What is the name of Matthew McConaughey's character in *Interstellar*?", "Cooper", "Miller", "Brand", "Doyle"});
        triviaMap.put(89, new String[]{"The Martian", "Who plays Mark Watney in *The Martian*?", "Matt Damon", "Tom Hanks", "Brad Pitt", "Ryan Gosling"});
        triviaMap.put(90, new String[]{"Deadpool 2", "What is the name of Deadpool's team in *Deadpool 2*?", "X-Force", "The Avengers", "Justice League", "Fantastic Four"});
        triviaMap.put(91, new String[]{"Rogue One: A Star Wars Story", "Who plays Jyn Erso in *Rogue One: A Star Wars Story*?", "Felicity Jones", "Natalie Portman", "Carrie Fisher", "Daisy Ridley"});
        triviaMap.put(92, new String[]{"The Hunger Games", "Who plays Katniss Everdeen in *The Hunger Games*?", "Jennifer Lawrence", "Emma Watson", "Kristen Stewart", "Shailene Woodley"});
        triviaMap.put(93, new String[]{"Avatar", "What is the name of the planet in *Avatar*?", "Pandora", "Mars", "Earth", "Titan"});
        triviaMap.put(94, new String[]{"Transformers", "Who directed *Transformers*?", "Michael Bay", "Steven Spielberg", "Ridley Scott", "James Cameron"});
        triviaMap.put(95, new String[]{"The Dark Knight Rises", "Who is the villain in *The Dark Knight Rises*?", "Bane", "Joker", "Ra's al Ghul", "Two-Face"});
        triviaMap.put(96, new String[]{"Shrek", "Who voices the character of Shrek?", "Mike Myers", "Eddie Murphy", "Cameron Diaz", "Antonio Banderas"});
        triviaMap.put(97, new String[]{"Toy Story", "What is the name of the cowboy doll in *Toy Story*?", "Woody", "Buzz Lightyear", "Slinky Dog", "Mr. Potato Head"});
        triviaMap.put(98, new String[]{"Guardians of the Galaxy Vol. 2", "What is the name of the villain in *Guardians of the Galaxy Vol. 2*?", "Ego the Living Planet", "Thanos", "Ronan the Accuser", "Nebula"});
        triviaMap.put(99, new String[]{"Skyfall", "Who plays James Bond in *Skyfall*?", "Daniel Craig", "Pierce Brosnan", "Sean Connery", "Roger Moore"});
        triviaMap.put(100, new String[]{"The Matrix Revolutions", "Which character says 'Everything that has a beginning has an end' in *The Matrix Revolutions*?", "The Oracle", "Neo", "Morpheus", "Agent Smith"}); }
}
